//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılan değişiklikler yanlış davranışlara neden olabilir ve
//     kod yeniden oluşturulursa kaybedilir.
// </auto-generated>
//------------------------------------------------------------------------------

namespace son_deneme.Account
{


    public partial class Lockout
    {
    }
}
